### PR TITLE
Removes term_freqs taxon_annotations corpus

### LINKED ISSUE #214: Fix failing v2-beta subsumer frequencies test
The `term frequencies for post-comp subsumers of entities` test is failing when using the [v2-beta kb.phenoscape API](https://dev.phenoscape.org/api/v2-beta)
```
Failure (test-freqs.R:142:3): term frequencies for post-comp subsumers of entities
any(freqs > 0) is not TRUE
```
https://github.com/phenoscape/rphenoscape/blob/b668eb99c7fd29dc24a2ee6dd4c7f19a48926aca/tests/testthat/test-freqs.R#L135-L142
The test fails because all frequencies are 0.

### PR DESCRIPTION
**Pull request by johnbradley**
Removes the ability to use `corpus = "taxon_annotations"` with `term_freqs()`.
This means the only `corpus` supported are "taxa" and "genes".
The `as` parameter is also restricted to "phenotype" now, because this is the only value supported by "taxa" and "genes".

Fixes #214

### CODE REVIEW

File: R/term-weights.R [hunk 1]
```diff
@@ -21,16 +16,23 @@
 #' KB v2.0 API, auto-determining the category of a post-composed term is no
 #' longer supported. If the list of terms is legitimately of different categories,
 #' determine (and possibly correct) categories beforehand using [term_category()].
+#' In earlier (<=0.2.x) releases the "taxon_annotations" corpus was supported, but
+#' this is no longer the case due to the inability to determine an accurate
+#' count for post-composed terms with the KB v2.0 API. This also means that the
+#' only supported value for the as parameter is "phenotype" since "entity" and
```
Comment (hlapp) [inline R/term-weights.R:22]:
```suggestion
#' only supported value for the `as` parameter is "phenotype" since "entity" and
```

File: R/term-weights.R [hunk 2]
```diff
@@ -21,16 +16,23 @@
...
+#' "quality" were only supported for the "taxon_annotations" corpus.
 #' @param x a vector or list of one or more terms, either as IRIs or as term
 #'   objects.
 #' @param as the category or categories of the input terms (see [term_category()]).
-#'   Supported categories are "entity", "quality", and "phenotype". The value
-#'   must either be a single category (applying to all terms), or a vector of
-#'   categories (of same length as `x`). The default is "entity".
+#'   Supported categories are "entity", "quality", and "phenotype". (At present,
+#'   support for "entity" and "quality" have been deprecated as of v0.3.x)
```
Comment (hlapp) [inline R/term-weights.R:28]:
```suggestion
#'   support for "entity" and "quality" has been disabled as of v0.3.0, pending full support from the KB API.)
```

File: R/term-weights.R [hunk 3]
```diff
@@ -21,16 +16,23 @@
...
+#'   The value must either be a single category (applying to all terms), or a vector of
+#'   categories (of same length as `x`). The default is phenotype".
```
Comment (hlapp) [inline R/term-weights.R:30]:
```suggestion
#'   categories (of same length as `x`). The default is "phenotype".
```

File: R/term-weights.R [hunk 4]
```diff
@@ -21,16 +16,23 @@
...
 #' @param corpus the name of the corpus for which to determine frequencies.
 #'   Supported values are "taxon_annotations", "taxa", "gene_annotations", and
 #'   "genes". (At present, support for "gene_annotations" is pending support in
```
Comment (hlapp) [inline R/term-weights.R:33]:
```suggestion
#'   "genes". (At present, support for "gene_annotations" and "taxon_annotations" is disabled, pending support in
```

File: R/term-weights.R [hunk 5]
```diff
@@ -21,16 +16,23 @@
...
-#'   the Phenoscape API.) The default is "taxon_annotations".
+#'   the Phenoscape API. The "taxon_annotations" corpus support has been deprecated
```
Comment (hlapp) [inline R/term-weights.R:34]:
```suggestion
#'   the Phenoscape KB API.)
```

File: R/term-weights.R [hunk 6]
```diff
@@ -21,16 +16,23 @@
...
+#'   as of v0.3.x) The default is "taxa".
```
Comment (hlapp) [inline R/term-weights.R:35]:
```suggestion
#'   The default is "taxa".
```

File: R/term-weights.R [hunk 7]
```diff
@@ -47,16 +49,15 @@
 #' @examples
 #' terms <- c("pectoral fin", "pelvic fin", "dorsal fin", "paired fin")
 #' IRIs <- sapply(terms, get_term_iri, as = "anatomy")
-#' term_freqs(IRIs, as = "entity")
+#' term_freqs(IRIs, as = "phenotype")
```
Comment (hlapp) [inline R/term-weights.R:52]: This won't work because the terms aren't phenotypes. I.e., we shouldn't "fix" code snippets like this mis-representing their category.

File: tests/testthat/test-freqs.R [hunk 8]
```diff
@@ -94,30 +94,14 @@ test_that("obtaining/calculating term frequencies", {
   tl <- c("pelvic fin", "pectoral fin", "forelimb", "hindlimb", "dorsal fin", "caudal fin")
   tt <- sapply(tl, get_term_iri, as = "anatomy", exactOnly = TRUE)
 
-  wt <- term_freqs(tt, as = "entity", corpus = "taxon_annotations")
+  wt <- term_freqs(tt, as = "phenotype")
```
Comment (hlapp) [inline tests/testthat/test-freqs.R:97]: Again, this won't work if we pretend the terms to be something that they're not.

File: tests/testthat/test-freqs.R [hunk 9]
```diff
@@ -94,30 +94,14 @@ test_that("obtaining/calculating term frequencies", {
...
   testthat::expect_is(wt, "numeric")
   testthat::expect_length(wt, length(tt))
   testthat::expect_true(all(wt >= 0))
   testthat::expect_true(all(wt <= 1))
 
-  wt1 <- term_freqs(tt, as = "entity")
+  wt1 <- term_freqs(tt, as = "phenotype", corpus = "taxa")
```
Comment (hlapp) [inline tests/testthat/test-freqs.R:103]: See above.

File: tests/testthat/test-freqs.R [hunk 10]
```diff
@@ -127,6 +111,8 @@ test_that("obtaining/calculating term frequencies", {
                                                          times = nrow(phens)-1),
                                                      "auto")))
   testthat::expect_error(term_freqs(phens$id, as = "entity", corpus = "taxa"))
+  testthat::expect_error(term_freqs(phens$id, as = "entity", corpus = "taxa"))
```
Comment (hlapp) [inline tests/testthat/test-freqs.R:114]: Isn't this the same line repeated twice?

**Review by hlapp — CHANGES_REQUESTED** [review]
See inline comments. As for `tests/testthat/test-semsim.R`, there's not much point in changing the corpus from taxon_annotations to taxa. It just makes the tests redundant (the full dataset is already tested for corpus taxa, testing a subsample is redundant). And the subsampling is so that the tests execute in reasonable time because taxon_annotations used to be very slow. Hopefully, once supported by the API directly, the subsampling for execution time reasons won't be necessary anymore.

File: R/term-weights.R (hunk 7 above)
Comment (johnbradley) [reply R/term-weights.R:52]: The category of various terms is still a little fuzzy for me. 
Would "pectoral fin present" be a phenotype term that a user would want to calculate frequency of?
I'm not sure what a good example of running term_freqs() with a phenotype term would look like.
Perhaps something like this:
```
phens <- get_phenotypes(entity = "pectoral fin", quality = "present")
term_freqs(phens$id, as="phenotype")
```

Comment (hlapp) [reply R/term-weights.R:52]: Yes. All terms returned by `get_phenotypes()` are of category phenotype. Entities are, for example, anatomical elements.  A phenotype is (in our logic model) a quality that inheres in an entity. So technically (or I should say logically), at the least in the original EQ model, phenotypes are subclasses of qualities.

Comment (johnbradley) [reply R/term-weights.R]: I removed this example since we already had a "phenotype" example below it.

File: tests/testthat/test-freqs.R (hunk 8 above)
Comment (johnbradley) [reply tests/testthat/test-freqs.R]: I replaced this test with a simpler one that just tests phenotype term frequencies.

**Comment by johnbradley** [comment]
For `tests/testthat/test-semsim.R` I removed the "taxon_annotations" portion of the failing test.

File: R/term-weights.R [hunk 11]
```diff
@@ -45,18 +47,13 @@
 #' @return a vector of frequencies as floating point numbers (between zero
 #'   and 1.0), of the same length (and ordering) as the input list of terms.
 #' @examples
-#' terms <- c("pectoral fin", "pelvic fin", "dorsal fin", "paired fin")
-#' IRIs <- sapply(terms, get_term_iri, as = "anatomy")
-#' term_freqs(IRIs, as = "entity")
-#' 
 #' phens <- get_phenotypes(entity = "basihyal bone")
-#' term_freqs(phens$id, as = "phenotype", corpus = "taxon_annotations")
-#' term_freqs(phens$id, as = "phenotype", corpus = "taxa")
```
Comment (hlapp) [inline R/term-weights.R:54]: Why not keep the "taxa" corpus example? It's the more relevant anyway.

File: tests/testthat/test-freqs.R [hunk 12]
```diff
@@ -91,33 +91,15 @@ test_that("obtaining corpus size", {
...
-  testthat::expect_false(all(wt1 == wt))
-  testthat::expect_true(all(wt1[1:5] == wt[1:5]))
-  testthat::expect_equal(wt1[6], 0)
-
-  phens <- get_phenotypes(entity = "pelvic fin", quality = "shape")
-  wt <- term_freqs(phens$id, as = "phenotype", corpus = "taxon_annotations")
-  testthat::expect_length(wt, nrow(phens))
-  testthat::expect_true(all(wt >= 0))
-  testthat::expect_true(all(wt <= 1))
   wt1 <- term_freqs(phens$id, as = "phenotype", corpus = "taxa")
```
Comment (hlapp) [inline tests/testthat/test-freqs.R:101]: So this tests whether `wt` used "taxa" as then default corpus, right? Maybe add that as a comment so it's clearer what's being tested for?

**Review by hlapp — APPROVED** [review]
See inline comments. These are minor, so I'm leaving their consideration to you.
